site_name: kiara_modules.network_analysis
repo_url: https://github.com/DHARPA-project/kiara_modules.network_analysis
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

extra_css:
  - stylesheets/extra.css

markdown_extensions:
- attr_list
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.snippets:
    base_path: docs

nav:
- Home: index.md
- Usage: usage.md
- Development: development.md
- Included modules: modules_list.md
- Included pipelines: pipelines_list.md
- Code Reference: reference/

extra:
  version:
    provider: mike

plugins:
- search
- mknotebooks
- mkdocstrings:
    default_handler: python
    watch:
      - "src"
    enable_inventory: true
- gen-files:
    scripts:
      - scripts/documentation/gen_ref_pages.py
      - scripts/documentation/gen_module_doc.py
- literate-nav:
    nav_file: SUMMARY.md
- macros:
   modules:
     - kiara.doc.mkdocs_macros_cli
     - kiara.doc.mkdocs_macros_kiara

#- frkl-docgen:
#    main_module: "kiara_modules.network_analysis"
